### ISSUE TITLE
Adapt to recent change in native requirements

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter.Core.Samples#17]
Was about to remove reference to Bluestar2, due to https://github.com/Starcounter/Announcements/issues/73, but realized this sample don't hold the promise of the README any more - it now requires preparing setup.

Since setup instructions is in Nova README, and Nova is private, I'm not sure what to do either.

@Mackiovello?

**Comment by ErlendLandro** [comment]
I think we should do the same as in https://github.com/Starcounter/Starcounter.Nova.Cli/issues/113, move the instructions away from the README and link to it here.
