### ISSUE TITLE
Rename to Starcounter.Nova.Samples

### ISSUE THREAD

**Issue by ErlendLandro** [Starcounter/Starcounter.Core.Samples#2]
Starcounter.Core is now called Starcounter.Nova, so this repository should be renamed as well

**Comment by ubbeK** [comment]
~~I think you are on top of it but make sure the TC builds are passing afterward.~~

Scratch that, I dont think it is a part of our Nova builds at the moment.

**Comment by ErlendLandro** [comment]
Code is update to use `Starcounter.Nova.Samples`. I'll rename this repo when the master build passes. Then, I'll probably have to change the link for the Travis svg

**Comment by ErlendLandro** [comment]
Done
